// File generated from our OpenAPI spec by Stainless.

package com.onebusawaykt.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class StopArrivalAndDepartureRetrieveResponseTest {

    @Test
    fun createStopArrivalAndDepartureRetrieveResponse() {
        val stopArrivalAndDepartureRetrieveResponse =
            StopArrivalAndDepartureRetrieveResponse.builder()
                .code(123L)
                .currentTime(123L)
                .data(
                    StopArrivalAndDepartureRetrieveResponse.Data.builder()
                        .entry(
                            StopArrivalAndDepartureRetrieveResponse.Data.Entry.builder()
                                .arrivalEnabled(true)
                                .blockTripSequence(123L)
                                .departureEnabled(true)
                                .numberOfStopsAway(123L)
                                .predictedArrivalTime(123L)
                                .predictedDepartureTime(123L)
                                .routeId("routeId")
                                .scheduledArrivalTime(123L)
                                .scheduledDepartureTime(123L)
                                .serviceDate(123L)
                                .stopId("stopId")
                                .stopSequence(123L)
                                .totalStopsInTrip(123L)
                                .tripHeadsign("tripHeadsign")
                                .tripId("tripId")
                                .vehicleId("vehicleId")
                                .actualTrack("actualTrack")
                                .distanceFromStop(42.23)
                                .frequency("frequency")
                                .historicalOccupancy("historicalOccupancy")
                                .lastUpdateTime(123L)
                                .occupancyStatus("occupancyStatus")
                                .predicted(true)
                                .predictedArrivalInterval("predictedArrivalInterval")
                                .predictedDepartureInterval("predictedDepartureInterval")
                                .predictedOccupancy("predictedOccupancy")
                                .routeLongName("routeLongName")
                                .routeShortName("routeShortName")
                                .scheduledArrivalInterval("scheduledArrivalInterval")
                                .scheduledDepartureInterval("scheduledDepartureInterval")
                                .scheduledTrack("scheduledTrack")
                                .situationIds(listOf("string"))
                                .status("status")
                                .tripStatus(
                                    StopArrivalAndDepartureRetrieveResponse.Data.Entry.TripStatus
                                        .builder()
                                        .activeTripId("activeTripId")
                                        .blockTripSequence(123L)
                                        .closestStop("closestStop")
                                        .distanceAlongTrip(42.23)
                                        .lastKnownDistanceAlongTrip(42.23)
                                        .lastLocationUpdateTime(123L)
                                        .lastUpdateTime(123L)
                                        .occupancyCapacity(123L)
                                        .occupancyCount(123L)
                                        .occupancyStatus("occupancyStatus")
                                        .phase("phase")
                                        .predicted(true)
                                        .scheduleDeviation(123L)
                                        .serviceDate(123L)
                                        .status("status")
                                        .totalDistanceAlongTrip(42.23)
                                        .closestStopTimeOffset(123L)
                                        .frequency("frequency")
                                        .lastKnownLocation(
                                            StopArrivalAndDepartureRetrieveResponse.Data.Entry
                                                .TripStatus
                                                .LastKnownLocation
                                                .builder()
                                                .lat(42.23)
                                                .lon(42.23)
                                                .build()
                                        )
                                        .lastKnownOrientation(42.23)
                                        .nextStop("nextStop")
                                        .nextStopTimeOffset(123L)
                                        .orientation(42.23)
                                        .position(
                                            StopArrivalAndDepartureRetrieveResponse.Data.Entry
                                                .TripStatus
                                                .Position
                                                .builder()
                                                .lat(42.23)
                                                .lon(42.23)
                                                .build()
                                        )
                                        .scheduledDistanceAlongTrip(42.23)
                                        .situationIds(listOf("string"))
                                        .vehicleId("vehicleId")
                                        .build()
                                )
                                .build()
                        )
                        .references(
                            StopArrivalAndDepartureRetrieveResponse.Data.References.builder()
                                .agencies(
                                    listOf(
                                        StopArrivalAndDepartureRetrieveResponse.Data.References
                                            .Agency
                                            .builder()
                                            .id("id")
                                            .name("name")
                                            .timezone("timezone")
                                            .url("url")
                                            .disclaimer("disclaimer")
                                            .email("email")
                                            .fareUrl("fareUrl")
                                            .lang("lang")
                                            .phone("phone")
                                            .privateService(true)
                                            .build()
                                    )
                                )
                                .routes(
                                    listOf(
                                        StopArrivalAndDepartureRetrieveResponse.Data.References
                                            .Route
                                            .builder()
                                            .id("id")
                                            .agencyId("agencyId")
                                            .type(123L)
                                            .color("color")
                                            .description("description")
                                            .longName("longName")
                                            .nullSafeShortName("nullSafeShortName")
                                            .shortName("shortName")
                                            .textColor("textColor")
                                            .url("url")
                                            .build()
                                    )
                                )
                                .situations(
                                    listOf(
                                        StopArrivalAndDepartureRetrieveResponse.Data.References
                                            .Situation
                                            .builder()
                                            .id("id")
                                            .creationTime(123L)
                                            .activeWindows(
                                                listOf(
                                                    StopArrivalAndDepartureRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .ActiveWindow
                                                        .builder()
                                                        .from(123L)
                                                        .to(123L)
                                                        .build()
                                                )
                                            )
                                            .allAffects(
                                                listOf(
                                                    StopArrivalAndDepartureRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .AllAffect
                                                        .builder()
                                                        .agencyId("agencyId")
                                                        .applicationId("applicationId")
                                                        .directionId("directionId")
                                                        .routeId("routeId")
                                                        .stopId("stopId")
                                                        .tripId("tripId")
                                                        .build()
                                                )
                                            )
                                            .consequenceMessage("consequenceMessage")
                                            .consequences(
                                                listOf(
                                                    StopArrivalAndDepartureRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .Consequence
                                                        .builder()
                                                        .condition("condition")
                                                        .conditionDetails(
                                                            StopArrivalAndDepartureRetrieveResponse
                                                                .Data
                                                                .References
                                                                .Situation
                                                                .Consequence
                                                                .ConditionDetails
                                                                .builder()
                                                                .diversionPath(
                                                                    StopArrivalAndDepartureRetrieveResponse
                                                                        .Data
                                                                        .References
                                                                        .Situation
                                                                        .Consequence
                                                                        .ConditionDetails
                                                                        .DiversionPath
                                                                        .builder()
                                                                        .length(123L)
                                                                        .levels("levels")
                                                                        .points("points")
                                                                        .build()
                                                                )
                                                                .diversionStopIds(listOf("string"))
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                            )
                                            .description(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .Description
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .publicationWindows(
                                                listOf(
                                                    StopArrivalAndDepartureRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .PublicationWindow
                                                        .builder()
                                                        .from(123L)
                                                        .to(123L)
                                                        .build()
                                                )
                                            )
                                            .reason(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .Reason
                                                    .EQUIPMENT_REASON
                                            )
                                            .severity("severity")
                                            .summary(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .Summary
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .url(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .Url
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                )
                                .stops(
                                    listOf(
                                        StopArrivalAndDepartureRetrieveResponse.Data.References.Stop
                                            .builder()
                                            .id("id")
                                            .code("code")
                                            .lat(42.23)
                                            .lon(42.23)
                                            .name("name")
                                            .direction("direction")
                                            .locationType(123L)
                                            .parent("parent")
                                            .routeIds(listOf("string"))
                                            .staticRouteIds(listOf("string"))
                                            .wheelchairBoarding("wheelchairBoarding")
                                            .build()
                                    )
                                )
                                .stopTimes(
                                    listOf(
                                        StopArrivalAndDepartureRetrieveResponse.Data.References
                                            .StopTime
                                            .builder()
                                            .arrivalTime(123L)
                                            .departureTime(123L)
                                            .distanceAlongTrip(42.23)
                                            .historicalOccupancy("historicalOccupancy")
                                            .stopHeadsign("stopHeadsign")
                                            .stopId("stopId")
                                            .build()
                                    )
                                )
                                .trips(
                                    listOf(
                                        StopArrivalAndDepartureRetrieveResponse.Data.References.Trip
                                            .builder()
                                            .id("id")
                                            .routeId("routeId")
                                            .serviceId("serviceId")
                                            .blockId("blockId")
                                            .directionId("directionId")
                                            .peakOffpeak(123L)
                                            .routeShortName("routeShortName")
                                            .shapeId("shapeId")
                                            .timeZone("timeZone")
                                            .tripHeadsign("tripHeadsign")
                                            .tripShortName("tripShortName")
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .build()
                )
                .text("text")
                .version(123L)
                .build()
        assertThat(stopArrivalAndDepartureRetrieveResponse).isNotNull
        assertThat(stopArrivalAndDepartureRetrieveResponse.code()).isEqualTo(123L)
        assertThat(stopArrivalAndDepartureRetrieveResponse.currentTime()).isEqualTo(123L)
        assertThat(stopArrivalAndDepartureRetrieveResponse.data())
            .isEqualTo(
                StopArrivalAndDepartureRetrieveResponse.Data.builder()
                    .entry(
                        StopArrivalAndDepartureRetrieveResponse.Data.Entry.builder()
                            .arrivalEnabled(true)
                            .blockTripSequence(123L)
                            .departureEnabled(true)
                            .numberOfStopsAway(123L)
                            .predictedArrivalTime(123L)
                            .predictedDepartureTime(123L)
                            .routeId("routeId")
                            .scheduledArrivalTime(123L)
                            .scheduledDepartureTime(123L)
                            .serviceDate(123L)
                            .stopId("stopId")
                            .stopSequence(123L)
                            .totalStopsInTrip(123L)
                            .tripHeadsign("tripHeadsign")
                            .tripId("tripId")
                            .vehicleId("vehicleId")
                            .actualTrack("actualTrack")
                            .distanceFromStop(42.23)
                            .frequency("frequency")
                            .historicalOccupancy("historicalOccupancy")
                            .lastUpdateTime(123L)
                            .occupancyStatus("occupancyStatus")
                            .predicted(true)
                            .predictedArrivalInterval("predictedArrivalInterval")
                            .predictedDepartureInterval("predictedDepartureInterval")
                            .predictedOccupancy("predictedOccupancy")
                            .routeLongName("routeLongName")
                            .routeShortName("routeShortName")
                            .scheduledArrivalInterval("scheduledArrivalInterval")
                            .scheduledDepartureInterval("scheduledDepartureInterval")
                            .scheduledTrack("scheduledTrack")
                            .situationIds(listOf("string"))
                            .status("status")
                            .tripStatus(
                                StopArrivalAndDepartureRetrieveResponse.Data.Entry.TripStatus
                                    .builder()
                                    .activeTripId("activeTripId")
                                    .blockTripSequence(123L)
                                    .closestStop("closestStop")
                                    .distanceAlongTrip(42.23)
                                    .lastKnownDistanceAlongTrip(42.23)
                                    .lastLocationUpdateTime(123L)
                                    .lastUpdateTime(123L)
                                    .occupancyCapacity(123L)
                                    .occupancyCount(123L)
                                    .occupancyStatus("occupancyStatus")
                                    .phase("phase")
                                    .predicted(true)
                                    .scheduleDeviation(123L)
                                    .serviceDate(123L)
                                    .status("status")
                                    .totalDistanceAlongTrip(42.23)
                                    .closestStopTimeOffset(123L)
                                    .frequency("frequency")
                                    .lastKnownLocation(
                                        StopArrivalAndDepartureRetrieveResponse.Data.Entry
                                            .TripStatus
                                            .LastKnownLocation
                                            .builder()
                                            .lat(42.23)
                                            .lon(42.23)
                                            .build()
                                    )
                                    .lastKnownOrientation(42.23)
                                    .nextStop("nextStop")
                                    .nextStopTimeOffset(123L)
                                    .orientation(42.23)
                                    .position(
                                        StopArrivalAndDepartureRetrieveResponse.Data.Entry
                                            .TripStatus
                                            .Position
                                            .builder()
                                            .lat(42.23)
                                            .lon(42.23)
                                            .build()
                                    )
                                    .scheduledDistanceAlongTrip(42.23)
                                    .situationIds(listOf("string"))
                                    .vehicleId("vehicleId")
                                    .build()
                            )
                            .build()
                    )
                    .references(
                        StopArrivalAndDepartureRetrieveResponse.Data.References.builder()
                            .agencies(
                                listOf(
                                    StopArrivalAndDepartureRetrieveResponse.Data.References.Agency
                                        .builder()
                                        .id("id")
                                        .name("name")
                                        .timezone("timezone")
                                        .url("url")
                                        .disclaimer("disclaimer")
                                        .email("email")
                                        .fareUrl("fareUrl")
                                        .lang("lang")
                                        .phone("phone")
                                        .privateService(true)
                                        .build()
                                )
                            )
                            .routes(
                                listOf(
                                    StopArrivalAndDepartureRetrieveResponse.Data.References.Route
                                        .builder()
                                        .id("id")
                                        .agencyId("agencyId")
                                        .type(123L)
                                        .color("color")
                                        .description("description")
                                        .longName("longName")
                                        .nullSafeShortName("nullSafeShortName")
                                        .shortName("shortName")
                                        .textColor("textColor")
                                        .url("url")
                                        .build()
                                )
                            )
                            .situations(
                                listOf(
                                    StopArrivalAndDepartureRetrieveResponse.Data.References
                                        .Situation
                                        .builder()
                                        .id("id")
                                        .creationTime(123L)
                                        .activeWindows(
                                            listOf(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .ActiveWindow
                                                    .builder()
                                                    .from(123L)
                                                    .to(123L)
                                                    .build()
                                            )
                                        )
                                        .allAffects(
                                            listOf(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .AllAffect
                                                    .builder()
                                                    .agencyId("agencyId")
                                                    .applicationId("applicationId")
                                                    .directionId("directionId")
                                                    .routeId("routeId")
                                                    .stopId("stopId")
                                                    .tripId("tripId")
                                                    .build()
                                            )
                                        )
                                        .consequenceMessage("consequenceMessage")
                                        .consequences(
                                            listOf(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .Consequence
                                                    .builder()
                                                    .condition("condition")
                                                    .conditionDetails(
                                                        StopArrivalAndDepartureRetrieveResponse.Data
                                                            .References
                                                            .Situation
                                                            .Consequence
                                                            .ConditionDetails
                                                            .builder()
                                                            .diversionPath(
                                                                StopArrivalAndDepartureRetrieveResponse
                                                                    .Data
                                                                    .References
                                                                    .Situation
                                                                    .Consequence
                                                                    .ConditionDetails
                                                                    .DiversionPath
                                                                    .builder()
                                                                    .length(123L)
                                                                    .levels("levels")
                                                                    .points("points")
                                                                    .build()
                                                            )
                                                            .diversionStopIds(listOf("string"))
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                        )
                                        .description(
                                            StopArrivalAndDepartureRetrieveResponse.Data.References
                                                .Situation
                                                .Description
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .publicationWindows(
                                            listOf(
                                                StopArrivalAndDepartureRetrieveResponse.Data
                                                    .References
                                                    .Situation
                                                    .PublicationWindow
                                                    .builder()
                                                    .from(123L)
                                                    .to(123L)
                                                    .build()
                                            )
                                        )
                                        .reason(
                                            StopArrivalAndDepartureRetrieveResponse.Data.References
                                                .Situation
                                                .Reason
                                                .EQUIPMENT_REASON
                                        )
                                        .severity("severity")
                                        .summary(
                                            StopArrivalAndDepartureRetrieveResponse.Data.References
                                                .Situation
                                                .Summary
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .url(
                                            StopArrivalAndDepartureRetrieveResponse.Data.References
                                                .Situation
                                                .Url
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                            )
                            .stops(
                                listOf(
                                    StopArrivalAndDepartureRetrieveResponse.Data.References.Stop
                                        .builder()
                                        .id("id")
                                        .code("code")
                                        .lat(42.23)
                                        .lon(42.23)
                                        .name("name")
                                        .direction("direction")
                                        .locationType(123L)
                                        .parent("parent")
                                        .routeIds(listOf("string"))
                                        .staticRouteIds(listOf("string"))
                                        .wheelchairBoarding("wheelchairBoarding")
                                        .build()
                                )
                            )
                            .stopTimes(
                                listOf(
                                    StopArrivalAndDepartureRetrieveResponse.Data.References.StopTime
                                        .builder()
                                        .arrivalTime(123L)
                                        .departureTime(123L)
                                        .distanceAlongTrip(42.23)
                                        .historicalOccupancy("historicalOccupancy")
                                        .stopHeadsign("stopHeadsign")
                                        .stopId("stopId")
                                        .build()
                                )
                            )
                            .trips(
                                listOf(
                                    StopArrivalAndDepartureRetrieveResponse.Data.References.Trip
                                        .builder()
                                        .id("id")
                                        .routeId("routeId")
                                        .serviceId("serviceId")
                                        .blockId("blockId")
                                        .directionId("directionId")
                                        .peakOffpeak(123L)
                                        .routeShortName("routeShortName")
                                        .shapeId("shapeId")
                                        .timeZone("timeZone")
                                        .tripHeadsign("tripHeadsign")
                                        .tripShortName("tripShortName")
                                        .build()
                                )
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(stopArrivalAndDepartureRetrieveResponse.text()).isEqualTo("text")
        assertThat(stopArrivalAndDepartureRetrieveResponse.version()).isEqualTo(123L)
    }
}
