// File generated from our OpenAPI spec by Stainless.

package com.onebusawaykt.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class StopScheduleForStopRetrieveResponseTest {

    @Test
    fun createStopScheduleForStopRetrieveResponse() {
        val stopScheduleForStopRetrieveResponse =
            StopScheduleForStopRetrieveResponse.builder()
                .code(123L)
                .currentTime(123L)
                .data(
                    StopScheduleForStopRetrieveResponse.Data.builder()
                        .entry(
                            StopScheduleForStopRetrieveResponse.Data.Entry.builder()
                                .date(123L)
                                .stopId("stopId")
                                .stopRouteSchedules(
                                    listOf(
                                        StopScheduleForStopRetrieveResponse.Data.Entry
                                            .StopRouteSchedule
                                            .builder()
                                            .routeId("routeId")
                                            .stopRouteDirectionSchedules(
                                                listOf(
                                                    StopScheduleForStopRetrieveResponse.Data.Entry
                                                        .StopRouteSchedule
                                                        .StopRouteDirectionSchedule
                                                        .builder()
                                                        .scheduleStopTimes(
                                                            listOf(
                                                                StopScheduleForStopRetrieveResponse
                                                                    .Data
                                                                    .Entry
                                                                    .StopRouteSchedule
                                                                    .StopRouteDirectionSchedule
                                                                    .ScheduleStopTime
                                                                    .builder()
                                                                    .arrivalEnabled(true)
                                                                    .arrivalTime(123L)
                                                                    .departureEnabled(true)
                                                                    .departureTime(123L)
                                                                    .serviceId("serviceId")
                                                                    .tripId("tripId")
                                                                    .stopHeadsign("stopHeadsign")
                                                                    .build()
                                                            )
                                                        )
                                                        .tripHeadsign("tripHeadsign")
                                                        .scheduleFrequencies(
                                                            listOf(
                                                                StopScheduleForStopRetrieveResponse
                                                                    .Data
                                                                    .Entry
                                                                    .StopRouteSchedule
                                                                    .StopRouteDirectionSchedule
                                                                    .ScheduleFrequency
                                                                    .builder()
                                                                    .endTime(123L)
                                                                    .headway(123L)
                                                                    .serviceDate(123L)
                                                                    .serviceId("serviceId")
                                                                    .startTime(123L)
                                                                    .tripId("tripId")
                                                                    .build()
                                                            )
                                                        )
                                                        .build()
                                                )
                                            )
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .references(
                            StopScheduleForStopRetrieveResponse.Data.References.builder()
                                .agencies(
                                    listOf(
                                        StopScheduleForStopRetrieveResponse.Data.References.Agency
                                            .builder()
                                            .id("id")
                                            .name("name")
                                            .timezone("timezone")
                                            .url("url")
                                            .disclaimer("disclaimer")
                                            .email("email")
                                            .fareUrl("fareUrl")
                                            .lang("lang")
                                            .phone("phone")
                                            .privateService(true)
                                            .build()
                                    )
                                )
                                .routes(
                                    listOf(
                                        StopScheduleForStopRetrieveResponse.Data.References.Route
                                            .builder()
                                            .id("id")
                                            .agencyId("agencyId")
                                            .type(123L)
                                            .color("color")
                                            .description("description")
                                            .longName("longName")
                                            .nullSafeShortName("nullSafeShortName")
                                            .shortName("shortName")
                                            .textColor("textColor")
                                            .url("url")
                                            .build()
                                    )
                                )
                                .situations(
                                    listOf(
                                        StopScheduleForStopRetrieveResponse.Data.References
                                            .Situation
                                            .builder()
                                            .id("id")
                                            .creationTime(123L)
                                            .activeWindows(
                                                listOf(
                                                    StopScheduleForStopRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .ActiveWindow
                                                        .builder()
                                                        .from(123L)
                                                        .to(123L)
                                                        .build()
                                                )
                                            )
                                            .allAffects(
                                                listOf(
                                                    StopScheduleForStopRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .AllAffect
                                                        .builder()
                                                        .agencyId("agencyId")
                                                        .applicationId("applicationId")
                                                        .directionId("directionId")
                                                        .routeId("routeId")
                                                        .stopId("stopId")
                                                        .tripId("tripId")
                                                        .build()
                                                )
                                            )
                                            .consequenceMessage("consequenceMessage")
                                            .consequences(
                                                listOf(
                                                    StopScheduleForStopRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .Consequence
                                                        .builder()
                                                        .condition("condition")
                                                        .conditionDetails(
                                                            StopScheduleForStopRetrieveResponse.Data
                                                                .References
                                                                .Situation
                                                                .Consequence
                                                                .ConditionDetails
                                                                .builder()
                                                                .diversionPath(
                                                                    StopScheduleForStopRetrieveResponse
                                                                        .Data
                                                                        .References
                                                                        .Situation
                                                                        .Consequence
                                                                        .ConditionDetails
                                                                        .DiversionPath
                                                                        .builder()
                                                                        .length(123L)
                                                                        .levels("levels")
                                                                        .points("points")
                                                                        .build()
                                                                )
                                                                .diversionStopIds(listOf("string"))
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                            )
                                            .description(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .Description
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .publicationWindows(
                                                listOf(
                                                    StopScheduleForStopRetrieveResponse.Data
                                                        .References
                                                        .Situation
                                                        .PublicationWindow
                                                        .builder()
                                                        .from(123L)
                                                        .to(123L)
                                                        .build()
                                                )
                                            )
                                            .reason(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .Reason
                                                    .EQUIPMENT_REASON
                                            )
                                            .severity("severity")
                                            .summary(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .Summary
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .url(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .Url
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                )
                                .stops(
                                    listOf(
                                        StopScheduleForStopRetrieveResponse.Data.References.Stop
                                            .builder()
                                            .id("id")
                                            .code("code")
                                            .lat(42.23)
                                            .lon(42.23)
                                            .name("name")
                                            .direction("direction")
                                            .locationType(123L)
                                            .parent("parent")
                                            .routeIds(listOf("string"))
                                            .staticRouteIds(listOf("string"))
                                            .wheelchairBoarding("wheelchairBoarding")
                                            .build()
                                    )
                                )
                                .stopTimes(
                                    listOf(
                                        StopScheduleForStopRetrieveResponse.Data.References.StopTime
                                            .builder()
                                            .arrivalTime(123L)
                                            .departureTime(123L)
                                            .distanceAlongTrip(42.23)
                                            .historicalOccupancy("historicalOccupancy")
                                            .stopHeadsign("stopHeadsign")
                                            .stopId("stopId")
                                            .build()
                                    )
                                )
                                .trips(
                                    listOf(
                                        StopScheduleForStopRetrieveResponse.Data.References.Trip
                                            .builder()
                                            .id("id")
                                            .routeId("routeId")
                                            .serviceId("serviceId")
                                            .blockId("blockId")
                                            .directionId("directionId")
                                            .peakOffpeak(123L)
                                            .routeShortName("routeShortName")
                                            .shapeId("shapeId")
                                            .timeZone("timeZone")
                                            .tripHeadsign("tripHeadsign")
                                            .tripShortName("tripShortName")
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .build()
                )
                .text("text")
                .version(123L)
                .build()
        assertThat(stopScheduleForStopRetrieveResponse).isNotNull
        assertThat(stopScheduleForStopRetrieveResponse.code()).isEqualTo(123L)
        assertThat(stopScheduleForStopRetrieveResponse.currentTime()).isEqualTo(123L)
        assertThat(stopScheduleForStopRetrieveResponse.data())
            .isEqualTo(
                StopScheduleForStopRetrieveResponse.Data.builder()
                    .entry(
                        StopScheduleForStopRetrieveResponse.Data.Entry.builder()
                            .date(123L)
                            .stopId("stopId")
                            .stopRouteSchedules(
                                listOf(
                                    StopScheduleForStopRetrieveResponse.Data.Entry.StopRouteSchedule
                                        .builder()
                                        .routeId("routeId")
                                        .stopRouteDirectionSchedules(
                                            listOf(
                                                StopScheduleForStopRetrieveResponse.Data.Entry
                                                    .StopRouteSchedule
                                                    .StopRouteDirectionSchedule
                                                    .builder()
                                                    .scheduleStopTimes(
                                                        listOf(
                                                            StopScheduleForStopRetrieveResponse.Data
                                                                .Entry
                                                                .StopRouteSchedule
                                                                .StopRouteDirectionSchedule
                                                                .ScheduleStopTime
                                                                .builder()
                                                                .arrivalEnabled(true)
                                                                .arrivalTime(123L)
                                                                .departureEnabled(true)
                                                                .departureTime(123L)
                                                                .serviceId("serviceId")
                                                                .tripId("tripId")
                                                                .stopHeadsign("stopHeadsign")
                                                                .build()
                                                        )
                                                    )
                                                    .tripHeadsign("tripHeadsign")
                                                    .scheduleFrequencies(
                                                        listOf(
                                                            StopScheduleForStopRetrieveResponse.Data
                                                                .Entry
                                                                .StopRouteSchedule
                                                                .StopRouteDirectionSchedule
                                                                .ScheduleFrequency
                                                                .builder()
                                                                .endTime(123L)
                                                                .headway(123L)
                                                                .serviceDate(123L)
                                                                .serviceId("serviceId")
                                                                .startTime(123L)
                                                                .tripId("tripId")
                                                                .build()
                                                        )
                                                    )
                                                    .build()
                                            )
                                        )
                                        .build()
                                )
                            )
                            .build()
                    )
                    .references(
                        StopScheduleForStopRetrieveResponse.Data.References.builder()
                            .agencies(
                                listOf(
                                    StopScheduleForStopRetrieveResponse.Data.References.Agency
                                        .builder()
                                        .id("id")
                                        .name("name")
                                        .timezone("timezone")
                                        .url("url")
                                        .disclaimer("disclaimer")
                                        .email("email")
                                        .fareUrl("fareUrl")
                                        .lang("lang")
                                        .phone("phone")
                                        .privateService(true)
                                        .build()
                                )
                            )
                            .routes(
                                listOf(
                                    StopScheduleForStopRetrieveResponse.Data.References.Route
                                        .builder()
                                        .id("id")
                                        .agencyId("agencyId")
                                        .type(123L)
                                        .color("color")
                                        .description("description")
                                        .longName("longName")
                                        .nullSafeShortName("nullSafeShortName")
                                        .shortName("shortName")
                                        .textColor("textColor")
                                        .url("url")
                                        .build()
                                )
                            )
                            .situations(
                                listOf(
                                    StopScheduleForStopRetrieveResponse.Data.References.Situation
                                        .builder()
                                        .id("id")
                                        .creationTime(123L)
                                        .activeWindows(
                                            listOf(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .ActiveWindow
                                                    .builder()
                                                    .from(123L)
                                                    .to(123L)
                                                    .build()
                                            )
                                        )
                                        .allAffects(
                                            listOf(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .AllAffect
                                                    .builder()
                                                    .agencyId("agencyId")
                                                    .applicationId("applicationId")
                                                    .directionId("directionId")
                                                    .routeId("routeId")
                                                    .stopId("stopId")
                                                    .tripId("tripId")
                                                    .build()
                                            )
                                        )
                                        .consequenceMessage("consequenceMessage")
                                        .consequences(
                                            listOf(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .Consequence
                                                    .builder()
                                                    .condition("condition")
                                                    .conditionDetails(
                                                        StopScheduleForStopRetrieveResponse.Data
                                                            .References
                                                            .Situation
                                                            .Consequence
                                                            .ConditionDetails
                                                            .builder()
                                                            .diversionPath(
                                                                StopScheduleForStopRetrieveResponse
                                                                    .Data
                                                                    .References
                                                                    .Situation
                                                                    .Consequence
                                                                    .ConditionDetails
                                                                    .DiversionPath
                                                                    .builder()
                                                                    .length(123L)
                                                                    .levels("levels")
                                                                    .points("points")
                                                                    .build()
                                                            )
                                                            .diversionStopIds(listOf("string"))
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                        )
                                        .description(
                                            StopScheduleForStopRetrieveResponse.Data.References
                                                .Situation
                                                .Description
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .publicationWindows(
                                            listOf(
                                                StopScheduleForStopRetrieveResponse.Data.References
                                                    .Situation
                                                    .PublicationWindow
                                                    .builder()
                                                    .from(123L)
                                                    .to(123L)
                                                    .build()
                                            )
                                        )
                                        .reason(
                                            StopScheduleForStopRetrieveResponse.Data.References
                                                .Situation
                                                .Reason
                                                .EQUIPMENT_REASON
                                        )
                                        .severity("severity")
                                        .summary(
                                            StopScheduleForStopRetrieveResponse.Data.References
                                                .Situation
                                                .Summary
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .url(
                                            StopScheduleForStopRetrieveResponse.Data.References
                                                .Situation
                                                .Url
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                            )
                            .stops(
                                listOf(
                                    StopScheduleForStopRetrieveResponse.Data.References.Stop
                                        .builder()
                                        .id("id")
                                        .code("code")
                                        .lat(42.23)
                                        .lon(42.23)
                                        .name("name")
                                        .direction("direction")
                                        .locationType(123L)
                                        .parent("parent")
                                        .routeIds(listOf("string"))
                                        .staticRouteIds(listOf("string"))
                                        .wheelchairBoarding("wheelchairBoarding")
                                        .build()
                                )
                            )
                            .stopTimes(
                                listOf(
                                    StopScheduleForStopRetrieveResponse.Data.References.StopTime
                                        .builder()
                                        .arrivalTime(123L)
                                        .departureTime(123L)
                                        .distanceAlongTrip(42.23)
                                        .historicalOccupancy("historicalOccupancy")
                                        .stopHeadsign("stopHeadsign")
                                        .stopId("stopId")
                                        .build()
                                )
                            )
                            .trips(
                                listOf(
                                    StopScheduleForStopRetrieveResponse.Data.References.Trip
                                        .builder()
                                        .id("id")
                                        .routeId("routeId")
                                        .serviceId("serviceId")
                                        .blockId("blockId")
                                        .directionId("directionId")
                                        .peakOffpeak(123L)
                                        .routeShortName("routeShortName")
                                        .shapeId("shapeId")
                                        .timeZone("timeZone")
                                        .tripHeadsign("tripHeadsign")
                                        .tripShortName("tripShortName")
                                        .build()
                                )
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(stopScheduleForStopRetrieveResponse.text()).isEqualTo("text")
        assertThat(stopScheduleForStopRetrieveResponse.version()).isEqualTo(123L)
    }
}
