// File generated from our OpenAPI spec by Stainless.

package com.onebusawaykt.api.models

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class VehicleTripRetrieveResponseTest {

    @Test
    fun createVehicleTripRetrieveResponse() {
        val vehicleTripRetrieveResponse =
            VehicleTripRetrieveResponse.builder()
                .code(123L)
                .currentTime(123L)
                .data(
                    VehicleTripRetrieveResponse.Data.builder()
                        .entry(
                            VehicleTripRetrieveResponse.Data.Entry.builder()
                                .tripId("tripId")
                                .frequency("frequency")
                                .schedule(
                                    VehicleTripRetrieveResponse.Data.Entry.Schedule.builder()
                                        .nextTripId("nextTripId")
                                        .previousTripId("previousTripId")
                                        .stopTimes(
                                            listOf(
                                                VehicleTripRetrieveResponse.Data.Entry.Schedule
                                                    .StopTime
                                                    .builder()
                                                    .arrivalTime(123L)
                                                    .departureTime(123L)
                                                    .distanceAlongTrip(42.23)
                                                    .historicalOccupancy("historicalOccupancy")
                                                    .stopHeadsign("stopHeadsign")
                                                    .stopId("stopId")
                                                    .build()
                                            )
                                        )
                                        .timeZone("timeZone")
                                        .frequency("frequency")
                                        .build()
                                )
                                .serviceDate(123L)
                                .situationIds(listOf("string"))
                                .status(
                                    VehicleTripRetrieveResponse.Data.Entry.Status.builder()
                                        .activeTripId("activeTripId")
                                        .blockTripSequence(123L)
                                        .closestStop("closestStop")
                                        .distanceAlongTrip(42.23)
                                        .lastKnownDistanceAlongTrip(42.23)
                                        .lastLocationUpdateTime(123L)
                                        .lastUpdateTime(123L)
                                        .occupancyCapacity(123L)
                                        .occupancyCount(123L)
                                        .occupancyStatus("occupancyStatus")
                                        .phase("phase")
                                        .predicted(true)
                                        .scheduleDeviation(123L)
                                        .serviceDate(123L)
                                        .status("status")
                                        .totalDistanceAlongTrip(42.23)
                                        .closestStopTimeOffset(123L)
                                        .frequency("frequency")
                                        .lastKnownLocation(
                                            VehicleTripRetrieveResponse.Data.Entry.Status
                                                .LastKnownLocation
                                                .builder()
                                                .lat(42.23)
                                                .lon(42.23)
                                                .build()
                                        )
                                        .lastKnownOrientation(42.23)
                                        .nextStop("nextStop")
                                        .nextStopTimeOffset(123L)
                                        .orientation(42.23)
                                        .position(
                                            VehicleTripRetrieveResponse.Data.Entry.Status.Position
                                                .builder()
                                                .lat(42.23)
                                                .lon(42.23)
                                                .build()
                                        )
                                        .scheduledDistanceAlongTrip(42.23)
                                        .situationIds(listOf("string"))
                                        .vehicleId("vehicleId")
                                        .build()
                                )
                                .build()
                        )
                        .references(
                            VehicleTripRetrieveResponse.Data.References.builder()
                                .agencies(
                                    listOf(
                                        VehicleTripRetrieveResponse.Data.References.Agency.builder()
                                            .id("id")
                                            .name("name")
                                            .timezone("timezone")
                                            .url("url")
                                            .disclaimer("disclaimer")
                                            .email("email")
                                            .fareUrl("fareUrl")
                                            .lang("lang")
                                            .phone("phone")
                                            .privateService(true)
                                            .build()
                                    )
                                )
                                .routes(
                                    listOf(
                                        VehicleTripRetrieveResponse.Data.References.Route.builder()
                                            .id("id")
                                            .agencyId("agencyId")
                                            .type(123L)
                                            .color("color")
                                            .description("description")
                                            .longName("longName")
                                            .nullSafeShortName("nullSafeShortName")
                                            .shortName("shortName")
                                            .textColor("textColor")
                                            .url("url")
                                            .build()
                                    )
                                )
                                .situations(
                                    listOf(
                                        VehicleTripRetrieveResponse.Data.References.Situation
                                            .builder()
                                            .id("id")
                                            .creationTime(123L)
                                            .activeWindows(
                                                listOf(
                                                    VehicleTripRetrieveResponse.Data.References
                                                        .Situation
                                                        .ActiveWindow
                                                        .builder()
                                                        .from(123L)
                                                        .to(123L)
                                                        .build()
                                                )
                                            )
                                            .allAffects(
                                                listOf(
                                                    VehicleTripRetrieveResponse.Data.References
                                                        .Situation
                                                        .AllAffect
                                                        .builder()
                                                        .agencyId("agencyId")
                                                        .applicationId("applicationId")
                                                        .directionId("directionId")
                                                        .routeId("routeId")
                                                        .stopId("stopId")
                                                        .tripId("tripId")
                                                        .build()
                                                )
                                            )
                                            .consequenceMessage("consequenceMessage")
                                            .consequences(
                                                listOf(
                                                    VehicleTripRetrieveResponse.Data.References
                                                        .Situation
                                                        .Consequence
                                                        .builder()
                                                        .condition("condition")
                                                        .conditionDetails(
                                                            VehicleTripRetrieveResponse.Data
                                                                .References
                                                                .Situation
                                                                .Consequence
                                                                .ConditionDetails
                                                                .builder()
                                                                .diversionPath(
                                                                    VehicleTripRetrieveResponse.Data
                                                                        .References
                                                                        .Situation
                                                                        .Consequence
                                                                        .ConditionDetails
                                                                        .DiversionPath
                                                                        .builder()
                                                                        .length(123L)
                                                                        .levels("levels")
                                                                        .points("points")
                                                                        .build()
                                                                )
                                                                .diversionStopIds(listOf("string"))
                                                                .build()
                                                        )
                                                        .build()
                                                )
                                            )
                                            .description(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .Description
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .publicationWindows(
                                                listOf(
                                                    VehicleTripRetrieveResponse.Data.References
                                                        .Situation
                                                        .PublicationWindow
                                                        .builder()
                                                        .from(123L)
                                                        .to(123L)
                                                        .build()
                                                )
                                            )
                                            .reason(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .Reason
                                                    .EQUIPMENT_REASON
                                            )
                                            .severity("severity")
                                            .summary(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .Summary
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .url(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .Url
                                                    .builder()
                                                    .lang("lang")
                                                    .value("value")
                                                    .build()
                                            )
                                            .build()
                                    )
                                )
                                .stops(
                                    listOf(
                                        VehicleTripRetrieveResponse.Data.References.Stop.builder()
                                            .id("id")
                                            .code("code")
                                            .lat(42.23)
                                            .lon(42.23)
                                            .name("name")
                                            .direction("direction")
                                            .locationType(123L)
                                            .parent("parent")
                                            .routeIds(listOf("string"))
                                            .staticRouteIds(listOf("string"))
                                            .wheelchairBoarding("wheelchairBoarding")
                                            .build()
                                    )
                                )
                                .stopTimes(
                                    listOf(
                                        VehicleTripRetrieveResponse.Data.References.StopTime
                                            .builder()
                                            .arrivalTime(123L)
                                            .departureTime(123L)
                                            .distanceAlongTrip(42.23)
                                            .historicalOccupancy("historicalOccupancy")
                                            .stopHeadsign("stopHeadsign")
                                            .stopId("stopId")
                                            .build()
                                    )
                                )
                                .trips(
                                    listOf(
                                        VehicleTripRetrieveResponse.Data.References.Trip.builder()
                                            .id("id")
                                            .routeId("routeId")
                                            .serviceId("serviceId")
                                            .blockId("blockId")
                                            .directionId("directionId")
                                            .peakOffpeak(123L)
                                            .routeShortName("routeShortName")
                                            .shapeId("shapeId")
                                            .timeZone("timeZone")
                                            .tripHeadsign("tripHeadsign")
                                            .tripShortName("tripShortName")
                                            .build()
                                    )
                                )
                                .build()
                        )
                        .build()
                )
                .text("text")
                .version(123L)
                .build()
        assertThat(vehicleTripRetrieveResponse).isNotNull
        assertThat(vehicleTripRetrieveResponse.code()).isEqualTo(123L)
        assertThat(vehicleTripRetrieveResponse.currentTime()).isEqualTo(123L)
        assertThat(vehicleTripRetrieveResponse.data())
            .isEqualTo(
                VehicleTripRetrieveResponse.Data.builder()
                    .entry(
                        VehicleTripRetrieveResponse.Data.Entry.builder()
                            .tripId("tripId")
                            .frequency("frequency")
                            .schedule(
                                VehicleTripRetrieveResponse.Data.Entry.Schedule.builder()
                                    .nextTripId("nextTripId")
                                    .previousTripId("previousTripId")
                                    .stopTimes(
                                        listOf(
                                            VehicleTripRetrieveResponse.Data.Entry.Schedule.StopTime
                                                .builder()
                                                .arrivalTime(123L)
                                                .departureTime(123L)
                                                .distanceAlongTrip(42.23)
                                                .historicalOccupancy("historicalOccupancy")
                                                .stopHeadsign("stopHeadsign")
                                                .stopId("stopId")
                                                .build()
                                        )
                                    )
                                    .timeZone("timeZone")
                                    .frequency("frequency")
                                    .build()
                            )
                            .serviceDate(123L)
                            .situationIds(listOf("string"))
                            .status(
                                VehicleTripRetrieveResponse.Data.Entry.Status.builder()
                                    .activeTripId("activeTripId")
                                    .blockTripSequence(123L)
                                    .closestStop("closestStop")
                                    .distanceAlongTrip(42.23)
                                    .lastKnownDistanceAlongTrip(42.23)
                                    .lastLocationUpdateTime(123L)
                                    .lastUpdateTime(123L)
                                    .occupancyCapacity(123L)
                                    .occupancyCount(123L)
                                    .occupancyStatus("occupancyStatus")
                                    .phase("phase")
                                    .predicted(true)
                                    .scheduleDeviation(123L)
                                    .serviceDate(123L)
                                    .status("status")
                                    .totalDistanceAlongTrip(42.23)
                                    .closestStopTimeOffset(123L)
                                    .frequency("frequency")
                                    .lastKnownLocation(
                                        VehicleTripRetrieveResponse.Data.Entry.Status
                                            .LastKnownLocation
                                            .builder()
                                            .lat(42.23)
                                            .lon(42.23)
                                            .build()
                                    )
                                    .lastKnownOrientation(42.23)
                                    .nextStop("nextStop")
                                    .nextStopTimeOffset(123L)
                                    .orientation(42.23)
                                    .position(
                                        VehicleTripRetrieveResponse.Data.Entry.Status.Position
                                            .builder()
                                            .lat(42.23)
                                            .lon(42.23)
                                            .build()
                                    )
                                    .scheduledDistanceAlongTrip(42.23)
                                    .situationIds(listOf("string"))
                                    .vehicleId("vehicleId")
                                    .build()
                            )
                            .build()
                    )
                    .references(
                        VehicleTripRetrieveResponse.Data.References.builder()
                            .agencies(
                                listOf(
                                    VehicleTripRetrieveResponse.Data.References.Agency.builder()
                                        .id("id")
                                        .name("name")
                                        .timezone("timezone")
                                        .url("url")
                                        .disclaimer("disclaimer")
                                        .email("email")
                                        .fareUrl("fareUrl")
                                        .lang("lang")
                                        .phone("phone")
                                        .privateService(true)
                                        .build()
                                )
                            )
                            .routes(
                                listOf(
                                    VehicleTripRetrieveResponse.Data.References.Route.builder()
                                        .id("id")
                                        .agencyId("agencyId")
                                        .type(123L)
                                        .color("color")
                                        .description("description")
                                        .longName("longName")
                                        .nullSafeShortName("nullSafeShortName")
                                        .shortName("shortName")
                                        .textColor("textColor")
                                        .url("url")
                                        .build()
                                )
                            )
                            .situations(
                                listOf(
                                    VehicleTripRetrieveResponse.Data.References.Situation.builder()
                                        .id("id")
                                        .creationTime(123L)
                                        .activeWindows(
                                            listOf(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .ActiveWindow
                                                    .builder()
                                                    .from(123L)
                                                    .to(123L)
                                                    .build()
                                            )
                                        )
                                        .allAffects(
                                            listOf(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .AllAffect
                                                    .builder()
                                                    .agencyId("agencyId")
                                                    .applicationId("applicationId")
                                                    .directionId("directionId")
                                                    .routeId("routeId")
                                                    .stopId("stopId")
                                                    .tripId("tripId")
                                                    .build()
                                            )
                                        )
                                        .consequenceMessage("consequenceMessage")
                                        .consequences(
                                            listOf(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .Consequence
                                                    .builder()
                                                    .condition("condition")
                                                    .conditionDetails(
                                                        VehicleTripRetrieveResponse.Data.References
                                                            .Situation
                                                            .Consequence
                                                            .ConditionDetails
                                                            .builder()
                                                            .diversionPath(
                                                                VehicleTripRetrieveResponse.Data
                                                                    .References
                                                                    .Situation
                                                                    .Consequence
                                                                    .ConditionDetails
                                                                    .DiversionPath
                                                                    .builder()
                                                                    .length(123L)
                                                                    .levels("levels")
                                                                    .points("points")
                                                                    .build()
                                                            )
                                                            .diversionStopIds(listOf("string"))
                                                            .build()
                                                    )
                                                    .build()
                                            )
                                        )
                                        .description(
                                            VehicleTripRetrieveResponse.Data.References.Situation
                                                .Description
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .publicationWindows(
                                            listOf(
                                                VehicleTripRetrieveResponse.Data.References
                                                    .Situation
                                                    .PublicationWindow
                                                    .builder()
                                                    .from(123L)
                                                    .to(123L)
                                                    .build()
                                            )
                                        )
                                        .reason(
                                            VehicleTripRetrieveResponse.Data.References.Situation
                                                .Reason
                                                .EQUIPMENT_REASON
                                        )
                                        .severity("severity")
                                        .summary(
                                            VehicleTripRetrieveResponse.Data.References.Situation
                                                .Summary
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .url(
                                            VehicleTripRetrieveResponse.Data.References.Situation
                                                .Url
                                                .builder()
                                                .lang("lang")
                                                .value("value")
                                                .build()
                                        )
                                        .build()
                                )
                            )
                            .stops(
                                listOf(
                                    VehicleTripRetrieveResponse.Data.References.Stop.builder()
                                        .id("id")
                                        .code("code")
                                        .lat(42.23)
                                        .lon(42.23)
                                        .name("name")
                                        .direction("direction")
                                        .locationType(123L)
                                        .parent("parent")
                                        .routeIds(listOf("string"))
                                        .staticRouteIds(listOf("string"))
                                        .wheelchairBoarding("wheelchairBoarding")
                                        .build()
                                )
                            )
                            .stopTimes(
                                listOf(
                                    VehicleTripRetrieveResponse.Data.References.StopTime.builder()
                                        .arrivalTime(123L)
                                        .departureTime(123L)
                                        .distanceAlongTrip(42.23)
                                        .historicalOccupancy("historicalOccupancy")
                                        .stopHeadsign("stopHeadsign")
                                        .stopId("stopId")
                                        .build()
                                )
                            )
                            .trips(
                                listOf(
                                    VehicleTripRetrieveResponse.Data.References.Trip.builder()
                                        .id("id")
                                        .routeId("routeId")
                                        .serviceId("serviceId")
                                        .blockId("blockId")
                                        .directionId("directionId")
                                        .peakOffpeak(123L)
                                        .routeShortName("routeShortName")
                                        .shapeId("shapeId")
                                        .timeZone("timeZone")
                                        .tripHeadsign("tripHeadsign")
                                        .tripShortName("tripShortName")
                                        .build()
                                )
                            )
                            .build()
                    )
                    .build()
            )
        assertThat(vehicleTripRetrieveResponse.text()).isEqualTo("text")
        assertThat(vehicleTripRetrieveResponse.version()).isEqualTo(123L)
    }
}
