configured_endpoints: 28
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/private-quivalen%2Ftest1obw-sdk-d04668d97c66a80708cb1896ce9638dc2b55670ed447b67d9833f6a5349cc210.yml
