configured_endpoints: 28
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/private-quivalen%2Ftest1obw-sdk-abd0d4522003ff87d031bb62644d52026fe995c25ce4b62e82669e3fea5a4fae.yml
